---
title: "Introduction to OncoRegimenFinder"  
author: "Meera Y. Patel, MD"
description: > 
    Learn how to run OncoRegimenFinder 
output: 
    rmarkdown::html_vignette:
      df_print: kable
vignette: >
  %\VignetteIndexEntry{Introduction to OncoRegimenFinder}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  tidy = 'styler',
  collapse = TRUE,
  comment = "#>",
  cache = TRUE
)
```

# Load Packages  

```{r setup, eval=TRUE,echo=TRUE}
library(OncoRegimenFinder)
```

# Set Parameters

```{r parameters, echo=TRUE,eval=TRUE}
cdmDatabaseSchema <- "omop_cdm_2"
writeDatabaseSchema <- "oncoregimenfinder"
vocabularyTable <- "vocabulary"
drugExposureIngredientTable <- "ingredient_exposure"
regimenTable <- "regimen"
cohortTable <- "cohort"
regimenIngredientTable <- "regimen_ingredient"
```

# Run OncoRegimenFinder

```{r run,eval=FALSE,echo=TRUE}
runORF(conn = conn,
       cdmDatabaseSchema = cdmDatabaseSchema,
       writeDatabaseSchema = writeDatabaseSchema,
       vocabularyTable = vocabularyTable,
       drugExposureIngredientTable = drugExposureIngredientTable,
       cohortTable = cohortTable,
       regimenTable = regimenTable,
       regimenIngredientTable = regimenIngredientTable)
```

